### ISSUE TITLE
PipelineContext not found

### ISSUE THREAD

**Issue by rodeofive** [dalenewman/JunkDrawer#4]
I'm trying to get the solution to compile but for some reason the PipelineContext class isn't being found in one of the Pipeline dlls. You have the using Pipeline.Context statement and I pulled in the Pipeline dlls manually from the Package\Pipeline.Net folder. I couldn't find that library on NuGet, nor any info on the web about the Pipeline libraries, so I'm not sure where they came from. 

I'm using VS 2015 Enterprise. Any thoughts on what the problem could be?

**Comment by dalenewman** [comment]
I will get the solution updated.  I've been working off the source of the pipeline.net library which is still under development.  Thanks for your patience.

**Comment by dalenewman** [comment]
I updated the solution.  It includes the latest Pipeline.Net libraries.  It should build correctly now.  Please let me know if it doesn't.  Thanks.
